package ModuleCommon;


/**
 * Command protocoll for client / server communication.
 *
 * @author Chachulski, Mathea
 */
public enum Commands {
    CMD_GET_INVENTORY,
    CMD_GET_INVENTORY_RESP,
    CMD_GET_ITEMNUMBER,
    CMD_GET_ITEMNUMBER_RESP,
    CMD_GET_ITEMS_IN_CART_TO_PRINT_THEM,
    CMD_GET_ITEMS_IN_CART_TO_PRINT_THEM_RESP,
    CMD_GET_BULKSIZE, CMD_GET_BULKSIZE_RESP,
    CMD_LOGIN,
    CMD_LOGIN_RESP,
    CMD_DISPLAY_INFO,
    CMD_DISPLAY_INFO_RESP,
    CMD_SIGNUP_CUSTOMER,
    CMD_SIGNUP_CUSTOMER_RESP,
    CMD_SIGNUP_STAFF,
    CMD_SIGNUP_STAFF_RESP,
    CMD_LIST_ITEMS_BY_NUMBER,
    CMD_LIST_ITEMS_BY_NUMBER_RESP,
    CMD_LIST_ITEMS_BY_NAME,
    CMD_LIST_ITEMS_BY_NAME_RESP,
    CMD_SEARCH_ITEM_BY_NAME,
    CMD_SEARCH_ITEM_BY_NAME_RESP,
    CMD_IS_LOGGEDIN_AS,
    CMD_IS_LOGGEDIN_AS_RESP,
    CMD_ADD_ITEM,
    CMD_ADD_ITEM_RESP,
    CMD_RETURN_LOGLIST,
    CMD_RETURN_LOGLIST_RESP,
    CMD_RETURN_LOGLISTITEM_BY_DATE,
    CMD_RETURN_LOGLISTITEM_BY_DATE_RESP,
    CMD_ADD_TO_CART,
    CMD_ADD_TO_CART_RESP,
    CMD_INCREASE_AMOUNT_IN_CART,
    CMD_INCREASE_AMOUNT_IN_CART_RESP,
    CMD_INCREASE_STOCK,
    CMD_INCREASE_STOCK_RESP,
    CMD_VIEW_CART,
    CMD_VIEW_CART_RESP,
    CMD_PLACE_ORDER,
    CMD_PLACE_ORDER_RESP,
    CMD_CLEAR_CART,
    CMD_LOGOUT,
    CMD_SAVE_CURRENT_ITEMLIST,
    CMD_DELETE_ITEM,
    CMD_IS_BULKITEM,
    CMD_IS_BULKITEM_RESP
}
